"""Portable server defaults: real model columns, DDL compilers and DB-side inserts.

Live MySQL execution reuses these helpers from the isolated logs runner. This
suite requires no credentials and never imports the application's DB engine.
"""
from copy import copy
import pytest
import sqlalchemy as sa
from sqlalchemy.dialects import mysql, sqlite
from sqlalchemy.schema import CreateTable
import app.models  # register complete metadata
from app.db.base import Base

EXPECTED = {'agent_runs.latest_public_summary_json': {}, 'agent_run_commands.result_json': {}, 'agent_catalog_releases.manifest_json': {}, 'agent_provider_releases.tools_json': [], 'agent_provider_releases.capability_tags_json': [], 'agent_provider_releases.dependencies_json': [], 'agent_provider_releases.metadata_json': {}, 'agent_capability_definitions.description': '', 'agent_capability_definitions.input_schema_json': {}, 'agent_capability_definitions.output_schema_json': {}, 'agent_capability_definitions.context_bindings_json': [], 'agent_capability_definitions.capability_tags_json': [], 'agent_run_capability_snapshots.request_json': {}, 'agent_run_capability_snapshots.resolved_scope_json': {}, 'agent_run_capability_snapshots.selected_capability_ids_json': [], 'agent_run_capability_snapshots.exclusions_json': [], 'agent_capability_executions.input_json': {}, 'agent_capability_executions.output_json': {}, 'agent_quality_results.metrics_json': {}, 'agent_quality_findings.location_json': {}, 'agent_quality_findings.evidence_json': {}, 'agent_quality_findings.remediation_json': {}, 'agent_quality_gates.policy_json': {}, 'agent_artifact_lineages.metadata_json': {}, 'agent_context_snapshots.context_json': {}, 'agent_context_snapshot_refs.payload_json': {}, 'agent_plan_revisions.plan_json': {}, 'agent_conversation_summaries.summary_json': {}}


def model_column(key):
    table, column = key.split('.')
    return Base.metadata.tables[table].c[column]


def default_probe(key):
    """No Python default: omitted values must be generated by the database."""
    original = model_column(key)
    assert original.server_default is not None, key
    assert original.nullable is False, key
    return sa.Table('default_probe', sa.MetaData(),
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('value', copy(original.type), nullable=original.nullable,
                  server_default=sa.DefaultClause(original.server_default.arg)))


@pytest.mark.parametrize('key', sorted(EXPECTED))
@pytest.mark.parametrize('dialect', [mysql.dialect(), sqlite.dialect()], ids=['mysql','sqlite'])
def test_json_text_server_default_compiles_as_parenthesized_expression(key, dialect):
    original = model_column(key)
    expected = EXPECTED[key]
    literal = '{}' if expected == {} else '[]' if expected == [] else ''
    assert str(original.server_default.arg) == "('" + literal + "')", key
    ddl = str(CreateTable(default_probe(key)).compile(dialect=dialect))
    assert "DEFAULT ('" + literal + "')" in ddl, ddl
    assert 'NOT NULL' in ddl, ddl
    # Compile the real containing model table as well, including its FK clauses.
    ddl = str(CreateTable(original.table).compile(dialect=dialect))
    assert "DEFAULT ('" + literal + "')" in ddl


@pytest.mark.parametrize('key', sorted(EXPECTED))
def test_sqlite_omitted_value_uses_actual_server_default(key):
    table = default_probe(key)
    assert table.c.value.default is None
    engine = sa.create_engine('sqlite://')
    try:
        table.metadata.create_all(engine)
        with engine.begin() as connection:
            # Raw SQL deliberately bypasses ORM/client defaults.
            connection.exec_driver_sql('INSERT INTO default_probe (id) VALUES (1)')
            assert connection.scalar(sa.select(table.c.value)) == EXPECTED[key]
            with pytest.raises(sa.exc.IntegrityError):
                connection.exec_driver_sql('INSERT INTO default_probe (id,value) VALUES (2,NULL)')
    finally:
        engine.dispose()


def test_inventory_does_not_omit_new_json_text_defaults():
    discovered = {f'{t.name}.{c.name}' for t in Base.metadata.tables.values() for c in t.c
                  if isinstance(c.type.dialect_impl(mysql.dialect()), (sa.JSON, sa.Text))
                  and c.server_default is not None}
    assert discovered == set(EXPECTED)


@pytest.mark.parametrize('key', sorted(EXPECTED))
@pytest.mark.parametrize('broken', ['literal','missing','nullable'])
def test_reverse_validation_rejects_regressed_defaults(monkeypatch, key, broken):
    column = model_column(key)
    value = EXPECTED[key]
    literal = '{}' if value == {} else '[]' if value == [] else ''
    if broken == 'literal':
        monkeypatch.setattr(column, 'server_default', sa.DefaultClause(literal))
    elif broken == 'missing':
        monkeypatch.setattr(column, 'server_default', None)
    else:
        monkeypatch.setattr(column, 'nullable', True)
    with pytest.raises((AssertionError, AttributeError)):
        test_json_text_server_default_compiles_as_parenthesized_expression(key, mysql.dialect())
