import { test, expect } from '@playwright/test'
test('real HTTP 60s stream reconnects with accepted cursor, deduplicates and cancels on terminal', async ({ page, request }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/e2e/fixtures/sse-audit.html')
  await page.getByTestId('long').click()
  await expect(page.getByTestId('count')).toHaveText('2')
  await expect(page.getByTestId('status')).toHaveText('terminal', { timeout: 85000 })
  await expect(page.getByTestId('sequences')).toHaveText(JSON.stringify(Array.from({ length: 63 }, (_, i) => i + 1)))
  await expect(page.getByTestId('owners')).toHaveText('["run-a"]')
  await expect(page.getByTestId('terminal')).toHaveText('1')
  await expect(page.getByTestId('text')).toHaveText(Array.from({ length: 62 }, (_, i) => `片段${i + 1}|`).join(''))
  await page.waitForTimeout(2500) // prove no terminal reconnect after the retry interval
  const evidence = (await (await request.get('/__sse/evidence')).json()).filter((x: { key: string }) => x.key === 'long')
  expect(evidence).toHaveLength(2)
  expect(evidence[1]).toMatchObject({ query_cursor: '2', header_cursor: '2' })
  expect(evidence[1].ended - evidence[1].started).toBeGreaterThanOrEqual(60000)
  expect(evidence[1].ended - evidence[1].started).toBeLessThan(80000)
  expect(errors).toEqual([])
  await info.attach('real-http-evidence', { body: JSON.stringify(evidence, null, 2), contentType: 'application/json' })
})
test('real browser Run restart and switch cancel old sockets and isolate active projection', async ({ page, request }, info) => {
  await page.goto('/e2e/fixtures/sse-audit.html')
  await page.getByTestId('switch-a').click(); await expect(page.getByTestId('count')).toHaveText('1')
  await page.getByTestId('restart-a').click(); await expect(page.getByTestId('count')).toHaveText('1')
  await page.getByTestId('switch-b').click(); await expect(page.getByTestId('run')).toHaveText('run-b')
  await expect(page.getByTestId('status')).toHaveText('terminal', { timeout: 15000 })
  await expect(page.getByTestId('owners')).toHaveText('["run-b"]')
  await expect(page.getByTestId('sequences')).toHaveText('[1,2]')
  await expect(page.getByTestId('terminal')).toHaveText('1')
  const evidence = (await (await request.get('/__sse/evidence')).json()).filter((x: { key: string }) => x.key.startsWith('switch'))
  expect(evidence).toHaveLength(3)
  expect(evidence.slice(0, 2).every((x: { ended: number; started: number; frames: number }) => x.ended > 0 && x.ended - x.started < 5000 && x.frames === 1)).toBe(true)
  await info.attach('switch-http-evidence', { body: JSON.stringify(evidence, null, 2), contentType: 'application/json' })
})

